# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # database: <%= ENV["PRODUCTION_DB_NAME"] %>
  # username: <%= ENV["PRODUCTION_DB_USERNAME"] %>
  # password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
  database: postgres
  username: postgres
  password: password
  timeout: 50000

  # password: password
  # host: "<%= ENV.fetch("DB_SOCKET_DIR") { '/cloudsql' } %>/<%= ENV["CLOUD_SQL_CONNECTION_NAME"] %>"
  host: /cloudsql/backend-empathy-in-bytes-rails:asia-southeast1:backend-empathy-in-bytes-rails
  # host: "<%= File.join(ENV.fetch("DB_SOCKET_DIR") { '/cloudsql' }, ENV.fetch("CLOUD_SQL_CONNECTION_NAME") { 'backend-empathy-in-bytes-rails:asia-southeast1:backend-empathy-in-bytes-rails' }) %>"
  # host: 35.186.144.8
  # port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # database: <%= ENV["PRODUCTION_DB_NAME"] %>
  # username: <%= ENV["PRODUCTION_DB_USERNAME"] %>
  # password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
  database: postgres
  username: postgres
  password: password
  timeout: 10000

  # password: password
  # host: "<%= File.join(ENV.fetch("DB_SOCKET_DIR") { '/cloudsql' }, ENV.fetch("CLOUD_SQL_CONNECTION_NAME") { 'backend-empathy-in-bytes-rails:asia-southeast1:backend-empathy-in-bytes-rails' }) %>"
  # host: 35.186.144.8
  host: /cloudsql/backend-empathy-in-bytes-rails:asia-southeast1:backend-empathy-in-bytes-rails
  port: 5432

# tcp:
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   # database: <%= ENV["PRODUCTION_DB_NAME"] %>
#   # username: <%= ENV["PRODUCTION_DB_USERNAME"] %>
#   # password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
#   database: postgres
#   username: postgres
#   password: password
#   timeout: 10000

#   # password: password
#   # host: "<%= File.join(ENV.fetch("DB_SOCKET_DIR") { '/cloudsql' }, ENV.fetch("CLOUD_SQL_CONNECTION_NAME") { 'backend-empathy-in-bytes-rails:asia-southeast1:backend-empathy-in-bytes-rails' }) %>"
#   host: 35.186.144.8
#   port: 5432